version: 2
updates:
  - package-ecosystem: "npm" # Supports both npm and yarn projects
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    labels:
      - "dependencies"
      - "automerge-minor"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
