pull_request_rules:
  # Auto-merge dependabot PRs when CI passes
  - name: Auto-merge dependabot PRs
    conditions:
      - author=dependabot[bot]
      - check-success=lint-and-build
      - check-success=build
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - "#approved-reviews-by>=0"
    actions:
      merge:
        method: squash
      delete_head_branch: {}

  # Auto-merge PRs with automerge label
  - name: Auto-merge labeled PRs
    conditions:
      - label=automerge
      - check-success=lint-and-build  
      - check-success=build
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
      delete_head_branch: {}

  # Auto-merge minor/patch releases
  - name: Auto-merge minor updates
    conditions:
      - author=dependabot[bot]
      - title~=^Bump .* from .* to .*
      - -title~=BREAKING CHANGE
      - check-success=lint-and-build
      - check-success=build
    actions:
      merge:
        method: squash
      delete_head_branch: {}