name: Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited, ready_for_review]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  check_run:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request != null
    steps:
      - name: Auto-merge on approval and passing checks
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_message: pull-request-title-and-description
        env:
          MERGE_REQUIRED_APPROVALS: 1
          MERGE_DELETE_BRANCH: true
          MERGE_READY_STATE: clean
