name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.19
        uses: actions/setup-node@v4
        with:
          node-version: 20.19
      - run: yarn install
      - run: npx playwright install --with-deps
      - run: yarn test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
